# Generated by Django 4.2 on 2025-04-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('thumbnail', models.FileField(upload_to='')),
                ('video', models.FileField(upload_to='')),
                ('views', models.IntegerField(max_length=100)),
            ],
        ),
    ]
