# Generated by Django 4.2 on 2025-04-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_watch_later_view_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.FileField(upload_to='images/'),
        ),
    ]
